language: node_js
node_js: "10"
python: "3.7"

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

dist: bionic
addons:
  apt:
    packages:
      - python3-pip
      - python3-setuptools

before_install:
  - python3 -m pip install pre-commit==1.20.0
  - git diff --name-only $TRAVIS_COMMIT_RANGE | xargs pre-commit run --files

jobs:
  include:
    - stage: Test
      script:
        - npm run ci
    - stage: Deploy Windows & Mac
      if: tag IS present
      os: osx
      osx_image: xcode10.1
      script:
        - npm run release
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine
    - stage: Deploy linux
      if: tag IS present
      os: linux
      dist: bionic
      script:
        - npm run release

deploy:
  provider: releases
  api_key: $ENCRYPTED_GITHUB_TOKEN
  skip_cleanup: true
  on:
    tags: true
