# Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/ecosystems/javascript?view=azure-devops

strategy:
  matrix:
    linux:
      imageName: "ubuntu-18.04"
    mac:
      imageName: "macos-10.13"
    windows:
      imageName: "win1803"

pool:
  vmImage: $(imageName)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "13.x"
    displayName: "Install Node.js"

  - script: |
      npm i
      npm run ci
    displayName: "Build"

  # - task: GitHubRelease@1
  #   inputs:
  #     action: 'create'
  #     assets: |
  #       ./dist/*.snap
  #       ./dist/*.dmg
  #       ./dist/*.exe
  #       ./dist/*.AppImage
  #     changeLogCompareToRelease: 'lastFullRelease'
  #     changeLogType: 'commitBased'
  #     gitHubConnection: 'github.com_davegallant'
  #     repositoryName: 'davegallant/pocketcasts-electron'
  #     tagSource: 'auto'
  #     target: '$(Build.SourceVersion)'
  #   displayName: 'Create GitHub release'
    # condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master')
