# Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/ecosystems/javascript?view=azure-devops

strategy:
  matrix:
    linux:
      imageName: "ubuntu-18.04"
    # mac:
    #   imageName: "macos-10.13"
    # windows:
    #   imageName: "win1803"

pool:
  vmImage: $(imageName)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - script: |
      npm i
      npm run ci
    displayName: "Build"

  - script: |
      npm run release
    displayName: "Release"
    # condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master')

  - task: GitHubRelease@0
    inputs:
      gitHubConnection: davegallant
      repositoryName: davegallant/pocketcasts-electron
      tagSource: manual
      tag: $(Build.BuildNumber)
      assets: |
          $(Build.ArtifactStagingDirectory)/*.AppImage
          $(Build.ArtifactStagingDirectory)/*.dmg
          $(Build.ArtifactStagingDirectory)/*.exe
          $(Build.ArtifactStagingDirectory)/*.snap
    displayName: 'Create GitHub release'
    # condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master')
